; Script generated by Inno Setup Script Wizard.
; VK Ön Muhasebe - Windows Installer Setup Script (Supabase PostgreSQL Sürümü)

#define MyAppName "VK Ön Muhasebe"
#define MyAppVersion "2.0.0"
#define MyAppPublisher "VK Yazılım"
#define MyAppExeName "VK.exe"

[Setup]
AppId={{721355AD-4DFD-4B91-A50F-7A3B2EEBA60D}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={userpf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
OutputDir=Publish_Output\Installer
OutputBaseFilename=VK_On_Muhasebe_Kurulum
SetupIconFile=ErmayMuhasebe.Avalonia\ErmayMuhasebe.Avalonia\Assets\app.ico
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=lowest
ArchitecturesInstallIn64BitMode=x64compatible
CloseApplications=yes
RestartApplications=no

[Languages]
Name: "turkish"; MessagesFile: "compiler:Languages\Turkish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"
Name: "cleandatabase"; Description: "Temiz Kurulum: Mevcut yerel veritabanını sıfırla (Bütün eski test verilerini temizle)"; GroupDescription: "Veritabanı Seçenekleri:"; Flags: unchecked

[Files]
Source: "Publish_Output\Desktop\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\Assets\vk_app.ico"
Name: "{autoprograms}\{#MyAppName} Kaldır (Uninstall)"; Filename: "{uninstallexe}"; IconFilename: "{app}\Assets\vk_app.ico"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\Assets\vk_app.ico"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
var
  InfoPage: TOutputMsgWizardPage;
  SupabasePage: TInputQueryWizardPage;
  User1Page: TInputQueryWizardPage;
  User2Page: TInputQueryWizardPage;

function ExtractJsonValue(const Json, Key: String): String;
var
  P, P2, P3: Integer;
  SearchKey: String;
begin
  Result := '';
  SearchKey := '"' + Key + '":"';
  P := Pos(SearchKey, Json);
  if P > 0 then
  begin
    P2 := P + Length(SearchKey);
    P3 := Pos('"', Copy(Json, P2, Length(Json)));
    if P3 > 0 then
      Result := Copy(Json, P2, P3 - 1);
  end;
end;

procedure InitializeWizard;
var
  GuideText: String;
  ExistingCloudConfig: AnsiString;
begin
  // 1. Bilgilendirme / Rehber Ekranı
  GuideText := 
    'VK Ön Muhasebe kurulumuna hoş geldiniz!' + #13#10 + #13#10 +
    '📌 1. BULUT VERİTABANI (SUPABASE POSTGRESQL):' + #13#10 +
    '   - Kurulum esnasında kendi Supabase proje URL ve Anon API anahtarınızı girerek bulut senkronizasyonunu başlatabilirsiniz.' + #13#10 + #13#10 +
    '📌 2. YÖNETİCİ HESABI BELİRLEME:' + #13#10 +
    '   - Sisteme ilk girişte kullanacağınız yönetici kullanıcı adı ve şifrenizi belirleyebilirsiniz.' + #13#10 + #13#10 +
    '📌 3. FABRİKA AYARLARI & SIFIRLAMA GÜVENLİK ŞİFRESİ:' + #13#10 +
    '   - Sistemi sıfırlama, kullanıcı adı ve şifre değiştirme yetkisi için sizin belirleyeceğiniz onay şifreniz.' + #13#10 + #13#10 +
    'Kurulum sonrası program hemen açılacaktır.';

  InfoPage := CreateOutputMsgPage(wpSelectDir,
    'VK Ön Muhasebe Kurulum Bilgilendirmesi',
    'Sistem kurulum ve kullanıcı yapılandırma detayları:',
    GuideText);

  // 2. Supabase Bulut Veritabanı Yapılandırma Sayfası
  SupabasePage := CreateInputQueryPage(InfoPage.ID,
    'Supabase Bulut Veritabanı Yapılandırması',
    'Sistemin masaüstü ve mobil ile senkron çalışması için Supabase bilgilerinizi giriniz.',
    'Supabase Proje Bilgileri:');

  SupabasePage.Add('Supabase Proje URL (Örn: https://xxxx.supabase.co):', False);
  SupabasePage.Add('Supabase Anon / API Anahtarı (anon public key):', False);
  SupabasePage.Values[0] := '';
  SupabasePage.Values[1] := '';

  // Sistemde kayıtlı mevcut Supabase yapılandırması varsa otomatik doldur
  ExistingCloudConfig := '';
  if FileExists(ExpandConstant('{localappdata}') + '\ermay_cloud_config.json') then
  begin
    if LoadStringFromFile(ExpandConstant('{localappdata}') + '\ermay_cloud_config.json', ExistingCloudConfig) then
    begin
      SupabasePage.Values[0] := ExtractJsonValue(String(ExistingCloudConfig), 'BaseUrl');
      SupabasePage.Values[1] := ExtractJsonValue(String(ExistingCloudConfig), 'AuthSecret');
    end;
  end;

  // 3. Kullanıcı 1 (Ana Yönetici) ve Sistem Sıfırlama Şifresi Belirleme Sayfası
  User1Page := CreateInputQueryPage(SupabasePage.ID,
    'Kullanıcı Hesabı (Ana Yönetici) & Güvenlik Şifresi',
    'Sisteme giriş yapacak yönetici hesabınızı ve şifrenizi belirleyiniz.',
    'Yönetici bilgileri:');

  User1Page.Add('Yönetici Kullanıcı Adı (Zorunlu):', False);
  User1Page.Add('Yönetici Giriş Şifresi (Zorunlu):', True);
  User1Page.Add('Yönetici E-Posta Adresi (Şifre kurtarma için):', False);
  User1Page.Add('Fabrika Ayarları Sıfırlama Onay Şifresi (Zorunlu):', True);
  User1Page.Values[0] := '';
  User1Page.Values[1] := '';
  User1Page.Values[3] := '';

  // (SMTP sayfası tamamen kaldırıldı)

  // 5. Kullanıcı 2 (Ek Personel / Yedek Kullanıcı) Belirleme Sayfası
  User2Page := CreateInputQueryPage(User1Page.ID,
    'Kullanıcı Hesabı 2 (Opsiyonel İkinci Kullanıcı)',
    'Programa erişebilecek 2. Kullanıcıyı tanımlayabilirsiniz (İstemiyorsanız boş bırakabilirsiniz).',
    'Ek kullanıcı bilgileri:');

  User2Page.Add('2. Kullanıcı Adı (İsteğe bağlı):', False);
  User2Page.Add('2. Kullanıcı Şifresi:', True);
  User2Page.Add('2. Kullanıcı E-Posta Adresi:', False);
end;

procedure DeleteFilesByPattern(const Dir, Pattern: String);
var
  FindRec: TFindRec;
begin
  if FindFirst(Dir + '\' + Pattern, FindRec) then
  begin
    try
      repeat
        DeleteFile(Dir + '\' + FindRec.Name);
      until not FindNext(FindRec);
    finally
      FindClose(FindRec);
    end;
  end;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;
  if CurPageID = User1Page.ID then
  begin
    if (Trim(User1Page.Values[0]) = '') or (Trim(User1Page.Values[1]) = '') then
    begin
      MsgBox('Lütfen sisteme giriş için bir Yönetici Kullanıcı Adı ve Şifre belirleyiniz.', mbError, MB_OK);
      Result := False;
    end
    else if Trim(User1Page.Values[3]) = '' then
    begin
      MsgBox('Lütfen Fabrika Ayarları Sıfırlama Onay Şifresini belirleyiniz.', mbError, MB_OK);
      Result := False;
    end;
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  SupabaseUrlVal, SupabaseKeyVal, SmtpHostVal, SmtpPortVal, SmtpEmailVal, SmtpPassVal, User1Name, User1Pass, User1Email, User2Name, User2Pass, User2Email, FactoryResetPass, AppDataDir, ConfigPath, UserConfigPath, JsonContent, UserJsonContent, ScriptFile, ScriptContent: String;
  ExistingCloudConfig: AnsiString;
  ResultCode: Integer;
begin
  if CurStep = ssPostInstall then
  begin
    SupabaseUrlVal := Trim(SupabasePage.Values[0]);
    SupabaseKeyVal := Trim(SupabasePage.Values[1]);
    
    User1Name := Trim(User1Page.Values[0]);
    User1Pass := Trim(User1Page.Values[1]);
    User1Email := Trim(User1Page.Values[2]);

    User2Name := Trim(User2Page.Values[0]);
    User2Pass := Trim(User2Page.Values[1]);
    User2Email := Trim(User2Page.Values[2]);

    FactoryResetPass := Trim(User1Page.Values[3]);

    AppDataDir := ExpandConstant('{localappdata}');
    
    // 0. Temiz Kurulum: Veritabanı ve Bütün Eski Yapılandırmayı Sıfırla
    if WizardIsTaskSelected('cleandatabase') then
    begin
      // Form kutucukları boş bırakılmışsa mevcut dosyadan oku
      if (SupabaseUrlVal = '') or (SupabaseKeyVal = '') then
      begin
        if FileExists(AppDataDir + '\ermay_cloud_config.json') then
        begin
          if LoadStringFromFile(AppDataDir + '\ermay_cloud_config.json', ExistingCloudConfig) then
          begin
            if SupabaseUrlVal = '' then SupabaseUrlVal := ExtractJsonValue(String(ExistingCloudConfig), 'BaseUrl');
            if SupabaseKeyVal = '' then SupabaseKeyVal := ExtractJsonValue(String(ExistingCloudConfig), 'AuthSecret');
          end;
        end;
      end;

      ScriptFile := ExpandConstant('{tmp}\clean_install.ps1');
      ScriptContent :=
        '$ErrorActionPreference = ''SilentlyContinue''' + #13#10 +
        'Get-Process -Name ''VK'',''ErmayMuhasebe*'',''ErmayMuhasebe.Desktop'',''ErmayMuhasebe.Avalonia.Desktop'' -ErrorAction SilentlyContinue | Stop-Process -Force' + #13#10 +
        'Start-Sleep -Milliseconds 1000' + #13#10 +
        '$appDir = ''' + AppDataDir + '\ErmayMuhasebe''' + #13#10 +
        'if (Test-Path $appDir) {' + #13#10 +
        '  Get-ChildItem -Path $appDir -File -ErrorAction SilentlyContinue | ForEach-Object {' + #13#10 +
        '    if ($_.Name -like ''*.db*'' -or $_.Name -like ''*.db3*'' -or $_.Name -like ''*.wal'' -or $_.Name -like ''*.shm'' -or $_.Name -like ''*.json'' -or $_.Name -eq ''login_settings.txt'' -or $_.Name -eq ''company_logo.png'') {' + #13#10 +
        '      Remove-Item -Path $_.FullName -Force -ErrorAction SilentlyContinue' + #13#10 +
        '    }' + #13#10 +
        '  }' + #13#10 +
        '}' + #13#10 +
        'Remove-Item -Path ''' + AppDataDir + '\ermay_cloud_config.json'' -Force -ErrorAction SilentlyContinue' + #13#10;

      // Supabase bulut veritabanını da temizle
      if (SupabaseUrlVal <> '') and (SupabaseKeyVal <> '') then
      begin
        ScriptContent := ScriptContent +
          '$headers = @{ apikey = ''' + SupabaseKeyVal + '''; Authorization = ''Bearer ' + SupabaseKeyVal + ''' }' + #13#10 +
          '$tables = @(' + #13#10 +
          '  ''fatura_detaylar'',''siparis_detaylar'',''teklif_detaylar'',''stok_sayim_detaylari'',''musteri_takip_detaylar'',' + #13#10 +
          '  ''cari_hareketler'',''stok_hareketler'',''banka_hareketler'',''kasa_hareketler'',''kredi_karti_islemler'',''eft_islemler'',' + #13#10 +
          '  ''cekler'',''senetler'',''faturalar'',''siparisler'',''teklifler'',''stok_sayim_fisileri'',''musteri_takip_klasorler'',' + #13#10 +
          '  ''stoklar'',''cariler'',''bankalar'',''kasalar'',''doviz_kurlari'',''belge_arsiv'',''notlar'',''gorevler'',''personeller'',' + #13#10 +
          '  ''satis_hedefleri'',''haftalik_satis_hedefleri'',''yillik_satis_hedefleri'',''portfoy_kartlar'',''firma_profili'',''kullanicilar''' + #13#10 +
          ')' + #13#10 +
          'for ($pass = 1; $pass -le 3; $pass++) {' + #13#10 +
          '  foreach ($t in $tables) {' + #13#10 +
          '    try {' + #13#10 +
          '      Invoke-RestMethod -Uri (''' + SupabaseUrlVal + '/rest/v1/'' + $t + ''?id=gte.0'') -Method Delete -Headers $headers' + #13#10 +
          '    } catch {}' + #13#10 +
          '  }' + #13#10 +
          '}' + #13#10;
      end;

      SaveStringToFile(ScriptFile, ScriptContent, False);
      Exec('powershell.exe', '-NoProfile -ExecutionPolicy Bypass -File "' + ScriptFile + '"', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
      DeleteFile(ScriptFile);
    end;
    
    // 1. Supabase Bulut Yapılandırma Dosyasını Kaydet
    ConfigPath := AppDataDir + '\ermay_cloud_config.json';
    if (SupabaseUrlVal <> '') and (SupabaseKeyVal <> '') then
      JsonContent := '{"BaseUrl":"' + SupabaseUrlVal + '","AuthSecret":"' + SupabaseKeyVal + '","GoogleApiKey":"","GoogleClientId":"","GoogleClientSecret":"","IsActive":true,"IsAutoSyncEnabled":true}'
    else
      JsonContent := '{"BaseUrl":"","AuthSecret":"","GoogleApiKey":"","GoogleClientId":"","GoogleClientSecret":"","IsActive":false,"IsAutoSyncEnabled":false}';
    SaveStringToFile(ConfigPath, JsonContent, False);

    // 2. Kullanıcı/Şifre, SMTP ve Fabrika Sıfırlama Şifresi Dosyası Kaydet
    ForceDirectories(AppDataDir + '\ErmayMuhasebe');
    UserConfigPath := AppDataDir + '\ErmayMuhasebe\setup_initial_user.json';
    
    if User1Name <> '' then
    begin
      UserJsonContent := '{"Users":[' +
        '{"Username":"' + User1Name + '","Password":"' + User1Pass + '","Email":"' + User1Email + '"}' ;
      
      if (User2Name <> '') and (User2Pass <> '') then
      begin
        UserJsonContent := UserJsonContent + ',{"Username":"' + User2Name + '","Password":"' + User2Pass + '","Email":"' + User2Email + '"}';
      end;
      
      UserJsonContent := UserJsonContent + '],' ;
    end
    else
    begin
      UserJsonContent := '{"Users":[],' ;
    end;
    
    UserJsonContent := UserJsonContent +
      '"FactoryResetPassword":"' + FactoryResetPass + '",' +
      '"GoogleClientId":"",' +
      '"GoogleClientSecret":""}';
      
    SaveStringToFile(UserConfigPath, UserJsonContent, False);

    // 3. Kullanıcı Bilgilerini Doğrudan Supabase Bulutuna Kaydet
    if (SupabaseUrlVal <> '') and (SupabaseKeyVal <> '') and (User1Name <> '') then
    begin
      ScriptFile := ExpandConstant('{tmp}\sync_user_supabase.ps1');
      ScriptContent :=
        '$ErrorActionPreference = ''SilentlyContinue''' + #13#10 +
        '$headers = @{ apikey = ''' + SupabaseKeyVal + '''; Authorization = ''Bearer ' + SupabaseKeyVal + '''; Prefer = ''resolution=merge-duplicates''; ''Content-Type'' = ''application/json'' }' + #13#10 +
        '$u1 = ''' + User1Name + '''.Trim().ToLower()' + #13#10 +
        '$payload1 = @{ id = $u1; username = $u1; kullanici_adi = $u1; email = ''' + User1Email + '''; role = ''Admin''; rol = ''Admin''; is_active = $true; aktif_mi = $true; password_hash = ''temporary''; sifre = ''temporary'' } | ConvertTo-Json' + #13#10 +
        'Invoke-RestMethod -Uri (''' + SupabaseUrlVal + '/rest/v1/kullanicilar'') -Method Post -Headers $headers -Body $payload1' + #13#10;
        
      if (User2Name <> '') then
      begin
        ScriptContent := ScriptContent +
          '$u2 = ''' + User2Name + '''.Trim().ToLower()' + #13#10 +
          '$payload2 = @{ id = $u2; username = $u2; kullanici_adi = $u2; email = ''' + User2Email + '''; role = ''Admin''; rol = ''Admin''; is_active = $true; aktif_mi = $true; password_hash = ''temporary''; sifre = ''temporary'' } | ConvertTo-Json' + #13#10 +
          'Invoke-RestMethod -Uri (''' + SupabaseUrlVal + '/rest/v1/kullanicilar'') -Method Post -Headers $headers -Body $payload2' + #13#10;
      end;
      
      SaveStringToFile(ScriptFile, ScriptContent, False);
      Exec('powershell.exe', '-NoProfile -ExecutionPolicy Bypass -File "' + ScriptFile + '"', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
      DeleteFile(ScriptFile);
    end;
  end;
end;
