; Script generated by Inno Setup Script Wizard.
; VK Ön Muhasebe - Windows Installer Setup Script (Supabase PostgreSQL Sürümü)

#define MyAppName "VK Ön Muhasebe"
#define MyAppVersion "2.0.0"
#define MyAppPublisher "VK Yazılım"
#define MyAppExeName "VK.exe"

[Setup]
AppId={{721355AD-4DFD-4B91-A50F-7A3B2EEBA60D}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
OutputDir=Publish_Output\Installer
OutputBaseFilename=VK_On_Muhasebe_Kurulum
SetupIconFile=ErmayMuhasebe.Avalonia\ErmayMuhasebe.Avalonia\Assets\app.ico
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=lowest
ArchitecturesInstallIn64BitMode=x64compatible
CloseApplications=yes
RestartApplications=no

[Languages]
Name: "turkish"; MessagesFile: "compiler:Languages\Turkish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"
Name: "cleandatabase"; Description: "Temiz Kurulum: Mevcut yerel veritabanını sıfırla (Bütün eski test verilerini temizle)"; GroupDescription: "Veritabanı Seçenekleri:"; Flags: unchecked

[Files]
Source: "Publish_Output\Desktop\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\Assets\vk_app.ico"
Name: "{autoprograms}\{#MyAppName} Kaldır (Uninstall)"; Filename: "{uninstallexe}"; IconFilename: "{app}\Assets\vk_app.ico"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\Assets\vk_app.ico"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
var
  InfoPage: TOutputMsgWizardPage;
  SupabasePage: TInputQueryWizardPage;
  User1Page: TInputQueryWizardPage;
  EmailSmtpPage: TInputQueryWizardPage;
  User2Page: TInputQueryWizardPage;

procedure InitializeWizard;
var
  GuideText: String;
begin
  // 1. Bilgilendirme / Rehber Ekranı
  GuideText := 
    'VK Ön Muhasebe kurulumuna hoş geldiniz!' + #13#10 + #13#10 +
    '📌 1. BULUT VERİTABANI (SUPABASE POSTGRESQL):' + #13#10 +
    '   - Kurulum esnasında kendi Supabase proje URL ve Anon API anahtarınızı girerek bulut senkronizasyonunu başlatabilirsiniz.' + #13#10 + #13#10 +
    '📌 2. YÖNETİCİ HESABI BELİRLEME:' + #13#10 +
    '   - Sisteme ilk girişte kullanacağınız yönetici kullanıcı adı ve şifrenizi belirleyebilirsiniz.' + #13#10 + #13#10 +
    '📌 3. GMAIL İLE ŞİFRE SIFIRLAMA (İSTEĞE BAĞLI):' + #13#10 +
    '   - Şifre kurtarma e-postaları için Gmail uygulama şifresi tanımlayabilirsiniz.' + #13#10 + #13#10 +
    '📌 4. FABRİKA AYARLARI & SIFIRLAMA GÜVENLİK ŞİFRESİ:' + #13#10 +
    '   - Sistemi tamamen sıfırlama yetkisi için özel şifreniz (Varsayılan: VK2026).' + #13#10 + #13#10 +
    'Kurulum sonrası program hemen açılacaktır.';

  InfoPage := CreateOutputMsgPage(wpSelectDir,
    'VK Ön Muhasebe Kurulum Bilgilendirmesi',
    'Sistem kurulum ve kullanıcı yapılandırma detayları:',
    GuideText);

  // 2. Supabase Bulut Veritabanı Yapılandırma Sayfası
  SupabasePage := CreateInputQueryPage(InfoPage.ID,
    'Supabase Bulut Veritabanı Yapılandırması',
    'Sistemin masaüstü ve mobil ile senkron çalışması için Supabase bilgilerinizi giriniz.',
    'Supabase Proje Bilgileri:');

  SupabasePage.Add('Supabase Proje URL (Örn: https://xxxx.supabase.co):', False);
  SupabasePage.Add('Supabase Anon / API Anahtarı (anon public key):', False);
  SupabasePage.Values[0] := '';
  SupabasePage.Values[1] := '';

  // 3. Kullanıcı 1 (Ana Yönetici) ve Sistem Sıfırlama Şifresi Belirleme Sayfası
  User1Page := CreateInputQueryPage(SupabasePage.ID,
    'Kullanıcı Hesabı (Ana Yönetici) & Güvenlik Şifresi',
    'Sisteme giriş yapacak yönetici hesabınızı ve şifrenizi belirleyiniz.',
    'Yönetici bilgileri:');

  User1Page.Add('Yönetici Kullanıcı Adı (Zorunlu):', False);
  User1Page.Add('Yönetici Giriş Şifresi (Zorunlu):', True);
  User1Page.Add('Yönetici E-Posta Adresi (Şifre kurtarma için):', False);
  User1Page.Add('Fabrika Ayarları Sıfırlama Onay Şifresi:', True);
  User1Page.Values[0] := '';
  User1Page.Values[1] := '';
  User1Page.Values[3] := 'VK2026';

  // 4. Gmail / SMTP E-Posta Yapılandırma Sayfası (İsteğe bağlı)
  EmailSmtpPage := CreateInputQueryPage(User1Page.ID,
    'E-Posta & Şifre Sıfırlama Bildirimleri (İsteğe Bağlı)',
    'Şifre unutulduğunda e-posta ile kurtarma kodu göndermek için Gmail SMTP bilgilerinizi girebilirsiniz.',
    'Bu adımı boş bırakıp doğrudan devam edebilirsiniz:');

  EmailSmtpPage.Add('Gönderici Gmail / E-Posta Adresi (örn: muhasebe@gmail.com):', False);
  EmailSmtpPage.Add('Gmail 16 Haneli Uygulama Şifresi (App Password):', True);

  // 5. Kullanıcı 2 (Ek Personel / Yedek Kullanıcı) Belirleme Sayfası
  User2Page := CreateInputQueryPage(EmailSmtpPage.ID,
    'Kullanıcı Hesabı 2 (Opsiyonel İkinci Kullanıcı)',
    'Programa erişebilecek 2. Kullanıcıyı tanımlayabilirsiniz (İstemiyorsanız boş bırakabilirsiniz).',
    'Ek kullanıcı bilgileri:');

  User2Page.Add('2. Kullanıcı Adı (İsteğe bağlı):', False);
  User2Page.Add('2. Kullanıcı Şifresi:', True);
  User2Page.Add('2. Kullanıcı E-Posta Adresi:', False);
end;

procedure DeleteFilesByPattern(const Dir, Pattern: String);
var
  FindRec: TFindRec;
begin
  if FindFirst(Dir + '\' + Pattern, FindRec) then
  begin
    try
      repeat
        DeleteFile(Dir + '\' + FindRec.Name);
      until not FindNext(FindRec);
    finally
      FindClose(FindRec);
    end;
  end;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;
  if CurPageID = User1Page.ID then
  begin
    if (Trim(User1Page.Values[0]) = '') or (Trim(User1Page.Values[1]) = '') then
    begin
      MsgBox('Lütfen sisteme giriş için bir Yönetici Kullanıcı Adı ve Şifre belirleyiniz.', mbError, MB_OK);
      Result := False;
    end;
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  SupabaseUrlVal, SupabaseKeyVal, SmtpEmailVal, SmtpPassVal, User1Name, User1Pass, User1Email, User2Name, User2Pass, User2Email, FactoryResetPass, AppDataDir, ConfigPath, UserConfigPath, JsonContent, UserJsonContent: String;
  ResultCode: Integer;
begin
  if CurStep = ssPostInstall then
  begin
    SupabaseUrlVal := Trim(SupabasePage.Values[0]);
    SupabaseKeyVal := Trim(SupabasePage.Values[1]);

    SmtpEmailVal := Trim(EmailSmtpPage.Values[0]);
    SmtpPassVal := Trim(EmailSmtpPage.Values[1]);
    
    User1Name := Trim(User1Page.Values[0]);
    User1Pass := Trim(User1Page.Values[1]);
    User1Email := Trim(User1Page.Values[2]);

    User2Name := Trim(User2Page.Values[0]);
    User2Pass := Trim(User2Page.Values[1]);
    User2Email := Trim(User2Page.Values[2]);

    FactoryResetPass := Trim(User1Page.Values[3]);
    if FactoryResetPass = '' then FactoryResetPass := 'VK2026';

    AppDataDir := ExpandConstant('{localappdata}');
    
    // 0. Temiz Kurulum: Veritabanı ve Bütün Eski Yapılandırmayı Sıfırla
    if WizardIsTaskSelected('cleandatabase') then
    begin
      Exec('taskkill.exe', '/F /IM VK.exe', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
      Exec('taskkill.exe', '/F /IM ErmayMuhasebe.Desktop.exe', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
      Sleep(1000);

      DeleteFilesByPattern(AppDataDir + '\ErmayMuhasebe', '*.db*');
      DeleteFilesByPattern(AppDataDir + '\ErmayMuhasebe', '*.db3*');
      DeleteFilesByPattern(AppDataDir + '\ErmayMuhasebe', '*.json');
      DeleteFile(AppDataDir + '\ErmayMuhasebe\login_settings.txt');
      DeleteFile(AppDataDir + '\ErmayMuhasebe\company_logo.png');
      DeleteFile(AppDataDir + '\ermay_cloud_config.json');
    end;
    
    // 1. Supabase Bulut Yapılandırma Dosyasını Kaydet
    ConfigPath := AppDataDir + '\ermay_cloud_config.json';
    if (SupabaseUrlVal <> '') and (SupabaseKeyVal <> '') then
      JsonContent := '{"BaseUrl":"' + SupabaseUrlVal + '","AuthSecret":"' + SupabaseKeyVal + '","GoogleApiKey":"","GoogleClientId":"","GoogleClientSecret":"","IsActive":true,"IsAutoSyncEnabled":true}'
    else
      JsonContent := '{"BaseUrl":"","AuthSecret":"","GoogleApiKey":"","GoogleClientId":"","GoogleClientSecret":"","IsActive":false,"IsAutoSyncEnabled":false}';
    SaveStringToFile(ConfigPath, JsonContent, False);

    // 2. Kullanıcı/Şifre, SMTP ve Fabrika Sıfırlama Şifresi Dosyası Kaydet
    ForceDirectories(AppDataDir + '\ErmayMuhasebe');
    UserConfigPath := AppDataDir + '\ErmayMuhasebe\setup_initial_user.json';
    
    if User1Name <> '' then
    begin
      UserJsonContent := '{"Users":[' +
        '{"Username":"' + User1Name + '","Password":"' + User1Pass + '","Email":"' + User1Email + '"}' ;
      
      if (User2Name <> '') and (User2Pass <> '') then
      begin
        UserJsonContent := UserJsonContent + ',{"Username":"' + User2Name + '","Password":"' + User2Pass + '","Email":"' + User2Email + '"}';
      end;
      
      UserJsonContent := UserJsonContent + '],' ;
    end
    else
    begin
      UserJsonContent := '{"Users":[],' ;
    end;
    
    UserJsonContent := UserJsonContent +
      '"FactoryResetPassword":"' + FactoryResetPass + '",' +
      '"GoogleClientId":"",' +
      '"GoogleClientSecret":"",' +
      '"SmtpEmail":"' + SmtpEmailVal + '",' +
      '"SmtpPass":"' + SmtpPassVal + '"}';
      
    SaveStringToFile(UserConfigPath, UserJsonContent, False);
  end;
end;
