<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- FIX: Dizindeki virgül (,) karakterleri nedeniyle oluşan MSBuild hatasını engellemek için eklendi. -->
    <StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>
    <DisableStaticWebAssets>true</DisableStaticWebAssets>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\**" />
  </ItemGroup>


  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Humanizer" />
    <PackageReference Include="InfluxDB.Client" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="MiniExcel" />
    <PackageReference Include="MudBlazor" />
    <PackageReference Include="QuestPDF" />
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.HarfBuzz" />
    <PackageReference Include="sqlite-net-sqlcipher" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlcipher" />
  </ItemGroup>

</Project>
